# -*- coding: utf-8 -*-
#===============界面设计程序==============
#功能：界面控件生成、控件功能实现、数据库连接
#========================================

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QLineEdit

from Sql_fuc import *


#ui设计
class DBUi_mainWindow(Sql_fuc,QtWidgets.QMainWindow):
    def __init__(self):
        super(DBUi_mainWindow,self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1276, 565)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TextInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TextInput.setGeometry(QtCore.QRect(250, 30, 751, 41))
        self.TextInput.setObjectName("TextInput")
        self.IOhubInput = QtWidgets.QPushButton(self.centralwidget)
        self.IOhubInput.setGeometry(QtCore.QRect(130, 30, 111, 28))
        self.IOhubInput.setCheckable(False)
        self.IOhubInput.setChecked(False)
        self.IOhubInput.setObjectName("IOhubInput")
        self.TurnhubInput = QtWidgets.QPushButton(self.centralwidget)
        self.TurnhubInput.setGeometry(QtCore.QRect(10, 30, 111, 28))
        self.TurnhubInput.setObjectName("TurnhubInput")
        self.Material = QtWidgets.QPushButton(self.centralwidget)
        self.Material.setGeometry(QtCore.QRect(10, 170, 111, 28))
        self.Material.setObjectName("Material")
        self.Employee = QtWidgets.QPushButton(self.centralwidget)
        self.Employee.setGeometry(QtCore.QRect(130, 210, 111, 28))
        self.Employee.setObjectName("Employee")
        self.IOhub = QtWidgets.QPushButton(self.centralwidget)
        self.IOhub.setGeometry(QtCore.QRect(10, 210, 111, 28))
        self.IOhub.setObjectName("IOhub")
        self.Turnhub = QtWidgets.QPushButton(self.centralwidget)
        self.Turnhub.setGeometry(QtCore.QRect(130, 170, 111, 28))
        self.Turnhub.setObjectName("Turnhub")
        self.Hub = QtWidgets.QPushButton(self.centralwidget)
        self.Hub.setGeometry(QtCore.QRect(10, 250, 111, 28))
        self.Hub.setObjectName("Hub")
        self.Department = QtWidgets.QPushButton(self.centralwidget)
        self.Department.setGeometry(QtCore.QRect(130, 250, 111, 28))
        self.Department.setObjectName("Department")
        self.EmployeeInput = QtWidgets.QPushButton(self.centralwidget)
        self.EmployeeInput.setGeometry(QtCore.QRect(10, 110, 111, 28))
        self.EmployeeInput.setObjectName("EmployeeInput")
        self.MaterialInput = QtWidgets.QPushButton(self.centralwidget)
        self.MaterialInput.setGeometry(QtCore.QRect(130, 70, 111, 28))
        self.MaterialInput.setObjectName("MaterialInput")
        self.DepartmentInput = QtWidgets.QPushButton(self.centralwidget)
        self.DepartmentInput.setGeometry(QtCore.QRect(10, 70, 111, 28))
        self.DepartmentInput.setObjectName("DepartmentInput")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(250, 80, 751, 311))
        self.textBrowser.setObjectName("textBrowser")
        self.Hubnumber = QtWidgets.QPushButton(self.centralwidget)
        self.Hubnumber.setGeometry(QtCore.QRect(10, 350, 131, 28))
        self.Hubnumber.setObjectName("Hubnumber")
        self.Timenumber = QtWidgets.QPushButton(self.centralwidget)
        self.Timenumber.setGeometry(QtCore.QRect(10, 310, 131, 28))
        self.Timenumber.setObjectName("Timenumber")
        self.SeverID = QtWidgets.QLineEdit(self.centralwidget)
        self.SeverID.setGeometry(QtCore.QRect(1140, 100, 113, 21))
        self.SeverID.setObjectName("SeverID")
        self.pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.pwd.setGeometry(QtCore.QRect(1140, 220, 113, 21))
        self.pwd.setObjectName("pwd")
        self.Username = QtWidgets.QLineEdit(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(1140, 180, 113, 21))
        self.Username.setObjectName("Username")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1070, 220, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setObjectName("label_4")
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setGeometry(QtCore.QRect(1060, 270, 93, 28))
        self.LoginButton.setObjectName("LoginButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1040, 140, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1050, 180, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.DBname = QtWidgets.QLineEdit(self.centralwidget)
        self.DBname.setGeometry(QtCore.QRect(1140, 140, 113, 21))
        self.DBname.setObjectName("DBname")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1040, 100, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 390, 1211, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 420, 1211, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 450, 1171, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 480, 1211, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.UnloginButton = QtWidgets.QPushButton(self.centralwidget)
        self.UnloginButton.setGeometry(QtCore.QRect(1170, 270, 93, 28))
        self.UnloginButton.setObjectName("UnloginButton")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1276, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

        self.SeverID.setPlaceholderText('localhost')
        self.DBname.setPlaceholderText('DBname')
        self.Username.setPlaceholderText('username')
        self.pwd.setPlaceholderText('Password')
        self.pwd.setEchoMode(QLineEdit.Password)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "仓库物料管理系统v1.0"))
        self.TextInput.setPlaceholderText(_translate("mainWindow", "请输入相关信息"))
        self.IOhubInput.setText(_translate("mainWindow", "出入库输入"))
        self.TurnhubInput.setText(_translate("mainWindow", "转仓表输入"))
        self.Material.setText(_translate("mainWindow", "物料表"))
        self.Employee.setText(_translate("mainWindow", "员工表"))
        self.IOhub.setText(_translate("mainWindow", "出入库表"))
        self.Turnhub.setText(_translate("mainWindow", "转仓表"))
        self.Hub.setText(_translate("mainWindow", "仓库表"))
        self.Department.setText(_translate("mainWindow", "部门表"))
        self.EmployeeInput.setText(_translate("mainWindow", "员工表输入"))
        self.MaterialInput.setText(_translate("mainWindow", "物料表输入"))
        self.DepartmentInput.setText(_translate("mainWindow", "部门表输入"))
        self.Hubnumber.setText(_translate("mainWindow", "指定仓库库存查询"))
        self.Timenumber.setText(_translate("mainWindow", "时间段内出入查询"))
        self.label_4.setText(_translate("mainWindow", "密码："))
        self.LoginButton.setText(_translate("mainWindow", "登录"))
        self.label_2.setText(_translate("mainWindow", "数据库名："))
        self.label_3.setText(_translate("mainWindow", "用户名："))
        self.label.setText(_translate("mainWindow", "服务器名："))
        self.label_5.setText(_translate("mainWindow", "目前实现了的按钮功能包括 转仓表输入(输入格式：A202104160000,Y01814000,35,A0003,A0001），出入库输入(格式：A202104160000,Y01814000,A0003,35），"))
        self.label_6.setText(_translate("mainWindow", "物料表、转仓表、出入库表的查询，指定时间段（格式如：20210416,20210425 或 202104251200,202104252000 )内的出入库查询，指定仓库（格式：A0001 )库存查询"))
        self.label_7.setText(_translate("mainWindow", "在使用最左侧功能前，需要先在右侧连接到数据库，用户名和用户密码是本地数据库的登录名和密码，本地数据库怎么连接，在这就怎么连接，数据库名及用备"))
        self.label_8.setText(_translate("mainWindow", "份文件恢复后的数据库名。"))
        self.UnloginButton.setText(_translate("mainWindow", "注销"))

        #点击触发
        self.Material.clicked.connect(self.sql_selectMaterial)
        self.Turnhub.clicked.connect(self.sql_selectTurnhub)
        self.IOhub.clicked.connect(self.sql_selectIOhub)
        self.IOhubInput.clicked.connect(self.sql_IOhubInput)
        self.TurnhubInput.clicked.connect(self.sql_TurnhubInput)
        self.Hubnumber.clicked.connect(self.sql_HubnumberScl)
        self.Timenumber.clicked.connect(self.sql_TimenumberScl)
        self.LoginButton.clicked.connect(self.DBlogin)
        self.UnloginButton.clicked.connect(self.DBclose)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = DBUi_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())